Ds 434 hero banner
elpassion/flounder-2 pull request #188
Opened 2023-05-16 11:26 UTC by zuzannanap

2023-05-16 13:26 UTC, mzyznowska commented on packages/design-system/src/stories/molecules/HeroBanner/HeroBanner.stories.tsx
> +  title: "🟢 Molecules/HeroBanner",
```suggestion
  title: "🟠 Molecules/HeroBanner",
```

2023-05-16 13:33 UTC, mzyznowska commented
And loop doesn't work for me. I found that it could be something with the slides' width.

2023-05-16 18:47 UTC, kielbasa-elp requested changes
We have to create this component in different way because for now too much content is hardcoded. 

Maybe instead of preparing strict Slides, lets create just HeroBanner.Slide component which will be just wrapper for content with correct aspect ratio. Everything else would be define by users directly during creating slides.

2023-05-16 18:47 UTC, kielbasa-elp commented on packages/design-system/src/components/Carousel/Arrows/CarouselArrows.tsx
> +        "right-[5%]",
Do not change button styles. Instead of pass arrow buttons directly to the component with the new styles.

2023-05-22 13:18 UTC, mzyznowska approved these changes

2023-05-24 07:55 UTC, merged