Enable avatar inside `Chips` component
elpassion/flounder-2 pull request #25
Opened 2023-03-14 14:08 UTC by pauzim

2023-03-14 14:57 UTC, insanepl requested changes

2023-03-14 14:57 UTC, insanepl commented on packages/design-system/src/stories/utils.tsx
> +    <ImageTag
is Avatar component with size variant "xxs" too big?

2023-03-14 14:57 UTC, insanepl commented on packages/design-system/src/stories/utils.tsx
> +    <ImageTag
Also I see on Figma chips is always rounded, so maybe we shoudl code rounded variant inside Chips and just overflow-hidden on parent will take care of that

2023-03-14 15:46 UTC, pauzim commented on packages/design-system/src/stories/utils.tsx
> +    <ImageTag
I did this but with these styles icon doesn't fit and is clipped. Last time we discussed to get rid of variants but maybe we should use them and in this scenario icon won't be affected and only variant `avatar` will be rounded

2023-03-15 14:22 UTC, piotrekzawada approved these changes
LGTM

2023-03-15 14:27 UTC, merged