ELPDES-127 - file upload component
elpassion/flounder-2 pull request #27
Opened 2023-03-15 08:16 UTC by mzyznowska

2023-03-15 12:52 UTC, insanepl requested changes

2023-03-17 10:28 UTC, piotrekzawada commented on packages/design-system/src/components/FileUpload/DragAndDropFileUpload.tsx
> +          Drag & Drop or
let's add this text as prop

2023-03-17 10:28 UTC, piotrekzawada commented on packages/design-system/src/components/FileUpload/DragAndDropFileUpload.tsx
> +            Click to upload
let's add this text as prop

2023-03-17 10:30 UTC, piotrekzawada commented on packages/design-system/src/stories/atoms/Avatar.stories.tsx
> +import { storybookAvatarImageControl, storybookIconControl } from "../utils";
can we change it to absolute path?

2023-03-21 10:21 UTC, merged