RadioCard improvements
elpassion/flounder-2 pull request #300
Opened 2023-06-21 21:26 UTC by zuzannanap

2023-06-22 11:19 UTC, monikaracka requested changes
Figma:
<img width="141" alt="Screenshot 2023-06-22 at 13 08 26" src="https://github.com/elpassion/flounder-2/assets/91883425/85db5bc6-06fb-4d27-9cac-ec7b96a22452">
Storybook:
<img width="371" alt="Screenshot 2023-06-22 at 13 10 24" src="https://github.com/elpassion/flounder-2/assets/91883425/a1a5184b-6e1e-40f1-a5eb-011ed9feb82b">

⬆️  -styles are different here .

<img width="350" alt="Screenshot 2023-06-22 at 13 17 28" src="https://github.com/elpassion/flounder-2/assets/91883425/b8524ad5-d359-479e-a608-edd3cb45bce2">
 
⬆️  - we don't want this additional margin here.

2023-06-22 11:19 UTC, monikaracka commented on packages/design-system/src/stories/atoms/RadioCard.stories.tsx
>      },
```suggestion
    radioPosition: {
      control: "select"
    },
```

2023-06-22 11:19 UTC, monikaracka commented on packages/design-system/src/components/RadioCard/index.tsx
> +            "flex-row-reverse": radioPosition === "right",
Create styles with object like in other components e.g:
`const positionVariantStyles: GenericKeys = {
left: "flex-row",
right: "flex-row-reverse"
}`

2023-06-23 12:50 UTC, zuzannanap commented on packages/design-system/src/components/RadioCard/index.tsx
> +              hidden: size === "sm",
it happens while auto-saving document and works well

2023-06-23 13:11 UTC, monikaracka approved these changes

2023-06-23 13:38 UTC, merged