DS-558: fontWeights tokens
elpassion/flounder-2 pull request #303
Opened 2023-06-23 11:14 UTC by zuzannanap

2023-06-28 15:09 UTC, monikaracka commented on packages/design-system/src/components/Rating/index.tsx
> +      <p className="text-rating-supportingText font-rating-weightSupportingTexr mt-rating-marginSupportingText text-rating-base-supportingText empty:hidden">
```suggestion
      <p className="text-rating-supportingText font-rating-weightSupportingText mt-rating-marginSupportingText text-rating-base-supportingText empty:hidden">
```

2023-06-28 15:09 UTC, monikaracka commented on packages/design-system/src/components/Review/index.tsx
> +          <span className="font-medium text-review-base-listItemLabel">
missing token

2023-06-28 15:11 UTC, monikaracka commented on packages/design-system/src/components/Stepper/index.tsx
> +            "text-stepper-fontDescription font-stepper-weightDescriptio empty:hidden",
```suggestion
            "text-stepper-fontDescription font-stepper-weightDescription empty:hidden",
```

2023-06-28 15:12 UTC, monikaracka commented on packages/design-system/src/components/Toast/index.tsx
> +        "text-toast-fontDescription font-normal font-toast-weightDescription",
```suggestion
        "text-toast-fontDescription font-toast-weightDescription",
```

2023-06-28 15:18 UTC, monikaracka commented on packages/design-system/src/helpers/tokens/checkbox.json
> +  "weightOptionalLabelText": {
Put it in order for token types. Ideally, we should have the same order in each JSON with tokens.

2023-06-28 15:19 UTC, monikaracka commented on packages/design-system/src/helpers/tokens/datePicker.json
> +  },
Same issue with the order here.

2023-06-28 15:20 UTC, monikaracka commented on packages/design-system/src/helpers/tokens/dropdown.json
> +  },
Same issue with the order here.

2023-06-28 15:21 UTC, monikaracka commented on packages/design-system/src/helpers/tokens/featuredText.json
> +  },
Same issue with the order here.

2023-06-28 21:38 UTC, zuzannanap commented on packages/design-system/src/helpers/tokens/tokensConfigs/fontWeights.json
> +}
yeah it's a good idea, i changed it

2023-06-29 06:40 UTC, monikaracka requested changes

2023-06-29 06:40 UTC, monikaracka commented on packages/design-system/src/helpers/tokens/accordion.json
> +          "value": "{semi-bold}",
In config is semibold.

2023-06-29 06:40 UTC, monikaracka commented on packages/design-system/src/helpers/tokens/tokensConfigs/fontWeights.json
> +}
I meant we should have each `font weight` (100, 200, 300,  ..., 900) in config.

2023-06-29 09:19 UTC, monikaracka commented on packages/design-system/src/helpers/defaultTheme.js
> +  fontWeightsTokens.getFontWeightsConfig(fontWeightsTokens);
You didn't add this to config.

2023-06-29 11:10 UTC, monikaracka approved these changes

2023-06-29 12:14 UTC, merged