Fix components with input
elpassion/flounder-2 pull request #31
Opened 2023-03-16 07:35 UTC by mzyznowska

This PR contains search improvement [ELPDES-124](https://elpassion.atlassian.net/browse/ELPDES-124?atlOrigin=eyJpIjoiYTRkMGQyNjE2ZTJjNGFiMmJlMDMwN2Y1M2JmZmRkMmYiLCJwIjoiaiJ9)

2023-03-16 10:33 UTC, insanepl requested changes

2023-03-16 10:33 UTC, insanepl commented on packages/design-system/src/svgs/XCircleSvg.tsx
> +export default UserSvg;
```suggestion
export default XCircleSvg;
```

2023-03-16 10:33 UTC, insanepl commented on packages/design-system/src/svgs/XCircleSvg.tsx
> +export default UserSvg;
Also I don't think it's necessary I just checked by paths, we already got this one https://github.com/elpassion/flounder-2/blob/main/packages/design-system/src/svgs/CircularCloseSvg.tsx

2023-03-16 10:33 UTC, insanepl commented on packages/design-system/src/components/InputAutocomplete/index.tsx
> +    setInputValue("");
Why we just don't add change handler so we cna pass value and handler to input form? Then we dont need to pass current.value and setInputValue, seems like overcomplication to me

2023-03-16 16:26 UTC, mzyznowska commented on packages/design-system/src/components/InputAutocomplete/index.tsx
> +    setInputValue("");
I removed `setInputValue("")` in this function(`clearInput`) because I forgot to do it but I need inputValue to pass it to dropdown. I don't know what solution do you propose.

2023-03-17 10:07 UTC, insanepl commented on packages/design-system/src/components/InputAutocomplete/index.tsx
> +    setInputValue("");
I mean that maybe we can pass onChange and value optionally as most libs do it, and we control value from top where component is mounted by wiring onChange to some setState or react hook form then value will come from controller

2023-03-17 10:34 UTC, piotrekzawada approved these changes
LGTM 🙏

2023-03-18 20:09 UTC, insanepl approved these changes

2023-03-21 10:27 UTC, merged