DS-611 - accordion tests
elpassion/flounder-2 pull request #346
Opened 2023-07-14 12:31 UTC by monikaracka

2023-07-17 08:38 UTC, zuzannanap requested changes

2023-07-17 08:38 UTC, zuzannanap commented on packages/design-system/src/components/Accordion/__tests__/Accordion.spec.tsx
> +    const firstAccordionBody = screen.getByTestId("accordion-1");
it would be nice if we have a class like "AccordionTestComponent"with methods like "mountComponent", "getFirstAccordion", "getFirstButton", "clickFirstButton" etc. - it makes tests much more readable

2023-07-17 08:38 UTC, zuzannanap commented on packages/design-system/src/components/Accordion/__tests__/Accordion.spec.tsx
> +    const view = mountComponent();
do we need this "view" variable? woudn't just "mountComponent()" be enough?

2023-07-17 08:38 UTC, zuzannanap commented on packages/design-system/src/components/Accordion/Accordion.interface.ts
> +  id: number;
adding id just for test-id is not the best option
you can search for it by e.g. getByText - it's a more recommended practice (it would be more similar to user experience)

2023-07-17 15:34 UTC, monikaracka commented on packages/design-system/src/components/Accordion/Accordion.interface.ts
> +  id: number;
I can't use getByText because it can only find the child that way.

2023-07-18 08:06 UTC, zuzannanap commented on packages/design-system/src/components/Accordion/Accordion.interface.ts
> +  id: number;
ahh right

2023-07-18 13:19 UTC, zuzannanap commented on packages/design-system/src/components/Accordion/__tests__/Accordion.spec.tsx
> +class AccordionObject {
maybe "AccordionTestComponent"?

2023-07-18 15:28 UTC, monikaracka commented on packages/design-system/src/components/Accordion/__tests__/Accordion.spec.tsx
> +class AccordionObject {
But it's not a component. It's an object like in the pattern's name.

2023-07-18 16:07 UTC, monikaracka commented on packages/design-system/src/components/Accordion/__tests__/Accordion.spec.tsx
> +  async clickAt(button: HTMLElement) {
Why do you think it's a better way to write this function?

2023-07-19 02:34 UTC, zuzannanap commented on packages/design-system/src/components/Accordion/__tests__/Accordion.spec.tsx
> +  async clickAt(button: HTMLElement) {
ok, you're right

2023-07-19 02:36 UTC, zuzannanap commented on packages/design-system/src/components/Accordion/__tests__/Accordion.spec.tsx
> +class AccordionObject {
sorry, it should be comment to line 27 and relate to:
```
export const Accordion = ({ ...props }: AccordionComponentProps) => {
  const [expandedId, setExpandedId] = useState<number>();

  return (
    <AccordionComponent
      {...props}
      onClick={(newId) => setExpandedId(newId)}
      expandedId={expandedId}
    />
  );
};
```

2023-07-19 03:18 UTC, zuzannanap commented on packages/design-system/src/components/Accordion/__tests__/Accordion.screen-object.tsx
> +    return fireEvent.click(button);
it's recommended to use user-event when it's possible
https://testing-library.com/docs/user-event/intro/#:~:text=Differences%20from%20fireEvent%20%E2%80%8B,additional%20checks%20along%20the%20way.

2023-07-19 11:37 UTC, zuzannanap approved these changes

2023-07-19 11:37 UTC, zuzannanap commented on packages/design-system/src/components/Accordion/__tests__/Accordion.screen-object.tsx
> +    return userEvent.click(button);
you can write just button.click(), but whatever you like :)

2023-07-19 11:44 UTC, merged