Ds 610 aria attributes part2
elpassion/flounder-2 pull request #355
Opened 2023-07-17 14:13 UTC by zuzannanap

2023-07-18 09:50 UTC, monikaracka requested changes

2023-07-18 09:50 UTC, monikaracka commented on packages/design-system/src/components/Dropdown/DropdownComponents.tsx
> +    toggleLabel,
I'm not sure that we need toggleLabel in dropdown option, and we can't pass it in e.g. SelectDropdown.

2023-07-18 09:50 UTC, monikaracka commented on packages/design-system/src/components/RangeSlider/RangeSlider.interface.ts
> +  };
```suggestion
    minValueSliderAriaLabel?: string;
    maxValueSliderAriaLabel?: string;
```
I agree with @kielbasa-elp we shouldn't make ariaLabels obligatory.

2023-07-18 09:50 UTC, monikaracka commented on packages/design-system/src/components/Toggle/index.tsx
> +            aria-label={label.ariaLabel || label.visibleLabel}
```suggestion
            aria-label={props["aria-label"] || "toggle"}
```
or
```suggestion
            aria-label={props["aria-label"] || label}
```

2023-07-18 09:50 UTC, monikaracka commented on packages/design-system/src/components/Toggle/Toggle.interface.ts
> +  label: label;
```suggestion
  label: string;
```
Label, which is an object, is not very intuitive.

2023-07-19 02:30 UTC, zuzannanap commented on packages/design-system/src/components/Dropdown/DropdownComponents.tsx
> +    toggleLabel,
but we don't have to - it's optional

2023-07-19 11:42 UTC, monikaracka requested changes
Update Toggle components in table utils

2023-07-21 09:26 UTC, kielbasa-elp approved these changes

2023-07-21 12:14 UTC, kielbasa-elp commented on packages/design-system/src/components/Stepper/Stepper.interface.ts
> +  stepButtonAriaLabel: string;
maybe we can extend stepProp by htmlButton props and pick aria-label etc?

2023-07-21 12:41 UTC, monikaracka approved these changes

2023-07-24 08:27 UTC, kielbasa-elp commented on packages/design-system/src/components/SidePanel/index.tsx
> +          iconName={iconButton.iconName}
Now i am thinking maybe its better to leave `icon` here instead of customIcon. It's a bit strange to use `IconButton` and pass a customIcon

2023-07-24 10:02 UTC, zuzannanap commented on packages/design-system/src/components/Stepper/Stepper.interface.ts
> +  stepButtonAriaLabel: string;
upsi, sure :)

2023-07-24 10:02 UTC, zuzannanap commented on packages/design-system/src/components/SidePanel/index.tsx
> +          iconName={iconButton.iconName}
ok ;(

2023-07-24 10:29 UTC, merged