Ds 622 accordion body resizing
elpassion/flounder-2 pull request #357
Opened 2023-07-18 05:05 UTC by zuzannanap

2023-07-18 10:11 UTC, monikaracka reviewed
It looks like something that we can reuse in other components. Creating a custom hook sounds like a good idea in this case. What do you think?

2023-07-19 11:33 UTC, kielbasa-elp requested changes
Do not use

2023-07-19 11:33 UTC, kielbasa-elp commented on packages/design-system/src/components/Accordion/AccordionComponents.tsx
> +    const windowWidth = window.innerWidth;
Do not use window directly in component body like here because it will cause runtime error if not defined

2023-07-24 10:11 UTC, kielbasa-elp reviewed
There is useWindowSize hook already in utils folder. Maybe you can use it?

2023-07-24 12:49 UTC, kielbasa-elp approved these changes

2023-07-24 18:38 UTC, merged