Ds 638 sidebar tests
elpassion/flounder-2 pull request #366
Opened 2023-07-19 12:37 UTC by kielbasa-elp

2023-07-19 18:43 UTC, zuzannanap requested changes

2023-07-19 18:43 UTC, zuzannanap commented on packages/design-system/src/components/Sidebar/index.tsx
> +    collapsed: parentCollapsed,
why didn't you change it in the interface?

2023-07-19 18:43 UTC, zuzannanap commented on packages/design-system/src/components/Sidebar/index.tsx
> +        aria-label={isCollapsed ? "Expand sidebar" : "Collapse sidebar"}
it's ok, but only for english version

2023-07-19 18:43 UTC, zuzannanap commented on packages/design-system/src/components/Sidebar/__tests__/Sidebar.test.tsx
> +    return getByRole(this._container, "button", { name: /collapse sidebar/i });
we (Monika and me) use screen.getByRole - could you use it to make tests more consistent? Or are you doing it this way for a special purpose?

2023-07-19 18:43 UTC, zuzannanap commented on packages/design-system/src/components/Sidebar/__tests__/Sidebar.test.tsx
> +      await userEvent.click(this.toggleButton);
this.toggleButton.click() will work the same and will be consistent with other tests

2023-07-19 18:43 UTC, zuzannanap commented on packages/design-system/src/components/Sidebar/__tests__/Sidebar.test.tsx
> +class SidebarObject {
please move it to Sidebar.screen-object.tsx

2023-07-19 18:43 UTC, zuzannanap commented on packages/design-system/src/components/Sidebar/__tests__/Sidebar.test.tsx
> +    expect(sidebarObject.getSidebar()).toHaveAttribute(
wouldn't it be better to divide it for 2 separate tests? (only one assertion for a test is a good practice)

2023-07-19 18:43 UTC, zuzannanap commented
please change test.tsx for spec.tsx to be consistent with other tests :)

2023-07-19 20:43 UTC, kielbasa-elp commented on packages/design-system/src/components/Sidebar/index.tsx
> +    collapsed: parentCollapsed,
Why should I ? It's much better just to use e.g. `<Sidebar collapsed={true} />` than` <Sidebar parentCollapsed={true}/>` i think. Dev doesn't need to know what is going inside component

2023-07-19 20:47 UTC, kielbasa-elp commented on packages/design-system/src/components/Sidebar/__tests__/Sidebar.test.tsx
> +    return getByRole(this._container, "button", { name: /collapse sidebar/i });
This approach limit the search scope of the element and get button only from a given container, not from the entire body. It can be useful in some cases. 

But i got your point and sure, i will change it

2023-07-19 20:51 UTC, kielbasa-elp commented on packages/design-system/src/components/Sidebar/__tests__/Sidebar.test.tsx
> +class SidebarObject {
sure, but i am curious why "screen-object" ?

2023-07-19 20:57 UTC, kielbasa-elp commented on packages/design-system/src/components/Sidebar/index.tsx
> +        aria-label={isCollapsed ? "Expand sidebar" : "Collapse sidebar"}
Dev has possibility to pass custom ToggleButton with translated labels etc. I am not sure if it is necessary to add additional properties just for this case

2023-07-19 20:59 UTC, kielbasa-elp commented on packages/design-system/src/components/Sidebar/__tests__/Sidebar.test.tsx
> +    expect(sidebarObject.getSidebar()).toHaveAttribute(
I don't know 😄 i mean, i wanted to test collapse/expand functionality. I can create two separate tests and pass different initial state but, i think it won't be the same

2023-07-20 08:51 UTC, zuzannanap commented on packages/design-system/src/components/Sidebar/index.tsx
> +    collapsed: parentCollapsed,
okok

2023-07-20 08:52 UTC, zuzannanap commented on packages/design-system/src/components/Sidebar/index.tsx
> +        aria-label={isCollapsed ? "Expand sidebar" : "Collapse sidebar"}
yeah right

2023-07-20 15:34 UTC, monikaracka approved these changes

2023-07-21 07:35 UTC, merged