DS 717 - FileUploads error messages
elpassion/flounder-2 pull request #472
Opened 2023-08-14 11:55 UTC by zuzannanap

2023-08-16 08:40 UTC, monikaracka reviewed
<img width="370" alt="Screenshot 2023-08-16 at 10 32 27" src="https://github.com/elpassion/flounder-2/assets/91883425/d7dc1475-44fa-4d48-a0e9-1a3ecdc75cf0">
I'm not sure we should change supporting text `SVG, PNG, JPG or GIF. Max size of 2MB ` to an error message. Probably we have to wait for Paweł to get the answer.

2023-09-04 09:01 UTC, jakmarch requested changes

2023-09-04 09:01 UTC, jakmarch commented on packages/design-system/src/components/FileUpload/SmallFileUpload.tsx
> +        />
According to the designs, supporting text/err msg should be `text-sm`

2023-09-22 08:18 UTC, pauzim commented
What happens with this PR? 🤔

2023-10-12 09:02 UTC, closed without merging