fix/DS-870 - fixes after merge branch with tokens
elpassion/flounder-2 pull request #641
Opened 2023-10-12 14:21 UTC by monikaracka

2023-10-12 22:52 UTC, zuzannanap requested changes

2023-10-12 22:52 UTC, zuzannanap commented on packages/design-system/src/helpers/tokens/rating.json
> +    }
sth is still wron with height:
<img width="242" alt="image" src="https://github.com/elpassion/flounder-2/assets/105361496/91c3868c-f780-4dbc-b1f0-c1b07210223a">

2023-10-13 07:42 UTC, monikaracka commented on packages/design-system/src/helpers/tokens/rating.json
> +    }
Maybe try running your localhost again because `rating` looks good for me.

2023-10-16 05:24 UTC, olborska-elp commented
On my laptop pink ring looks quite good:

![Screenshot 2023-10-16 at 07 19 53](https://github.com/elpassion/flounder-2/assets/110667213/37020061-cacb-4cd8-9c61-b14886e00403)

2023-10-16 05:50 UTC, merged