ELPDES-92: Featured text component
elpassion/flounder-2 pull request #7
Opened 2023-03-08 21:48 UTC by pauzim

Designs: https://www.figma.com/file/xy6otn2JWHNdF70Tuq0UbS/TACO-Design-System-%5BDRAFT%5D?node-id=3896-36061&t=kfHLqXWPj8lXwNcw-0

I've separated `icon` and `imgSrc` props because of AC that we have to clip and fit icons if they are images. Not sure if this logic doesn't complicate this component too much. If for some reason both `icon` and `imgSrc` are provided, `imgSrc` has priority.

2023-03-09 08:54 UTC, insanepl reviewed
Remove package.lock and use pnpm to install. Might be some issues so wait for this after we merge (https://github.com/elpassion/flounder-2/pull/6)

2023-03-09 09:06 UTC, insanepl requested changes

2023-03-09 09:06 UTC, insanepl commented on packages/design-system/src/components/FeaturedText/index.tsx
> +    iconTop: "flex-col gap-y-4",
We can think about gaps already in figma tokens maybe? so we can customize spacing?

2023-03-09 09:06 UTC, insanepl commented on packages/design-system/src/components/FeaturedText/index.tsx
> +  const learnMoreSizeVariants = {
Same with the gaps and tokens I guess

2023-03-09 09:06 UTC, insanepl commented on packages/design-system/src/components/FeaturedText/index.tsx
> +          <span
How abouit if we just put {icon} here and pass svg, img, or font-icon from the to (storybook) as I did with NavTab

2023-03-09 09:06 UTC, insanepl commented on packages/design-system/src/components/FeaturedText/index.tsx
> +        <img
Can also be ditched if we just pass it as reactnode

2023-03-09 09:06 UTC, insanepl commented on packages/design-system/src/stories/molecules/FeaturedText.stories.tsx
> +    imageSrc: "images/rectangle.png",
Let 's put image/move images like this or avatar to storybook public, so it's not part of the lib: https://storybook.js.org/docs/react/configure/images-and-assets

2023-03-09 10:53 UTC, pauzim commented on packages/design-system/src/components/FeaturedText/index.tsx
> +        <img
It was my first approach but I stucked when it cames to fit passed img to specific size eg clip rectangle size to square etc 🤔

2023-03-09 16:27 UTC, insanepl commented on packages/design-system/src/components/FeaturedText/index.tsx
> +    sm: "w-4 h-4",
w-4 aspect-square and w-6 aspect-square should work

2023-03-09 16:27 UTC, insanepl commented on packages/design-system/src/components/FeaturedText/index.tsx
> +          <ArrowRight className={classNames(learnMoreIconSizes[size])} />
no need classNames here, Remember hat we're going to export all those components as a lib, so it's best if we stick to import react if possible

2023-03-10 14:32 UTC, insanepl requested changes
Add Arrow icon as RectCompoennt in svg folder, take a look at the main branch

2023-03-10 14:32 UTC, insanepl commented on packages/design-system/src/components/FeaturedText/index.tsx
> +import { ReactComponent as ArrowRight } from "../../svgs/arrow-right.svg";
Take a look how I handled Check User etc SVG. Let's use it this way, I found an issue while published to npm with those svgs :)

2023-03-10 15:51 UTC, pauzim commented on packages/design-system/src/components/FeaturedText/index.tsx
> +import { ReactComponent as ArrowRight } from "../../svgs/arrow-right.svg";
done!

2023-03-13 08:53 UTC, insanepl requested changes

2023-03-13 08:53 UTC, insanepl commented on packages/design-system/src/components/FeaturedText/index.tsx
> +    switch (size) {
Maybe we should use md as default size?

2023-03-13 08:53 UTC, insanepl commented on packages/design-system/src/svgs/ArrowRight.tsx
> +      height="24"
Remove

2023-03-13 11:46 UTC, insanepl requested changes

2023-03-13 11:46 UTC, insanepl commented on packages/design-system/src/stories/molecules/FeaturedText.stories.tsx
> +const StoryIcon: React.FC<{ src: string }> = ({ src }) => (
Move it to storybook utils.tsx, i made new file with control, icons and heleprs like this to keep stories clean :)

2023-03-13 11:46 UTC, insanepl commented on packages/design-system/src/stories/molecules/FeaturedText.stories.tsx
> +const StoryIcon: React.FC<{ src: string }> = ({ src }) => (
OHh I see there's more icons under it, maybe you can use the icons we alreayd got in helpers then :)

2023-03-13 11:46 UTC, insanepl commented on packages/design-system/src/svgs/ArrowRight.tsx
> +const ArrowRight = ({ className }: { className?: string }) => {
Pull main and use RightArrowSvg componen I already added, so we avoid duplocate code :) Also change import in compoennt you used it, as I checked it's literally the same code just formatted for JSX

2023-03-14 11:10 UTC, insanepl requested changes

2023-03-14 11:10 UTC, insanepl commented on packages/design-system/src/components/FeaturedText/index.tsx
> +
```suggestion
```

2023-03-14 11:10 UTC, insanepl commented on packages/design-system/src/components/FeaturedText/index.tsx
> +export const FeaturedText: React.FC<FeaturedTextProps> = ({
```suggestion
export const FeaturedText: FC<FeaturedTextProps> = ({
```

2023-03-14 11:28 UTC, pauzim commented on packages/design-system/src/components/FeaturedText/index.tsx
> +        <h6
Task added: https://elpassion.atlassian.net/jira/software/projects/ELPDES/boards/246?selectedIssue=ELPDES-158

2023-03-14 12:15 UTC, insanepl approved these changes

2023-03-14 13:14 UTC, merged